syncthing:
  image: xer0x/triton-syncthing
  links:
  - consul
  ports:
  - "8384:8384"
  restart: always
  mem_limit: 1024m
consul:
  image: gliderlabs/consul-server
  command: -bootstrap -ui-dir /ui
  expose:
  - 8400
  - 8500
  - 53:53/udp
  restart: always
  mem_limit: 256m
